#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm check-types
# TODO: the script below is not working. Need to evaluate what test left need to run after 
# code clean up and if Jest is still needed.
#pnpm test
